### ISSUE TITLE
[Bug] syntax error if there's no endline on the last line in a file

### ISSUE THREAD

**Issue by nateupstairs** [chaos-lang/chaos#45] opened 2020-04-26 22:57 UTC
code:
```
void def a()
  print "inside function a"
end
a()
```

i get a:
```
  Syntax error:
    Module: hello.kaos
    Line: 4
    Cause:
```
if there isn't an endline after a()
this threw me for a while, haha

**Comment by mertyildiran** [comment] 2020-04-27 21:03
@nateupstairs thank you so much your contribution! :blush: The issue is fixed with https://github.com/chaos-lang/chaos/commit/c80976ecaa8fae6f458a90bcb4e59388a808ef9a

**Closed by mertyildiran** 2020-04-27 21:03 UTC
